# Generated by Django 5.1.1 on 2024-09-13 10:44

import django.db.models.deletion
import sellit.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('ratings', models.IntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=512)),
                ('about', models.TextField(blank=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designate whether user can log on to admin site.')),
                ('subscription', models.CharField(choices=[('FF', 'FREE'), ('PP', 'PAID')], default='FF', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', sellit.models.user.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=512)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('whatsapp_no', models.CharField(blank=True, max_length=15)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('website', models.CharField(blank=True, max_length=512)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='sellit.store')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('NG', 'NAIRA'), ('US', 'DOLLAR')], default='NG', max_length=2)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=512)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sellit.store')),
            ],
        ),
    ]
